BASE_TASK_CONFIG_PATH: "configs/challenge-2021/challenge_pointnav2021.local.rgbd.yaml"
TRAINER_NAME: "ddppo"
ENV_NAME: "NavRLEnv"
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR"]

SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 4
NUM_UPDATES: 270000
CMD_TRAILING_OPTS: ["TASK_CONFIG.ENVIRONMENT.ITERATOR_OPTIONS.MAX_SCENE_REPEAT_STEPS", "50000"]
FORCE_TORCH_SINGLE_THREADED: True

LOG_INTERVAL: 10
LOG_FILE: "~/logs/pointnav-2021-baseline/train.log"
VIDEO_OPTION: ["tensorboard"]
TENSORBOARD_DIR: "~/logs/pointnav-2021-baseline/tb"

CHECKPOINT_FOLDER: "~/logs/pointnav-2021-baseline"
EVAL_CKPT_PATH_DIR: "~/logs/pointnav-2021-baseline"
NUM_CHECKPOINTS: -1
CHECKPOINT_INTERVAL: 500
EVAL_DURING_TRAIN: True
TEST_EPISODE_COUNT: -1
EVAL:
  USE_CKPT_CONFIG: True
  NUM_ENVIRONMENTS: 1
  SPLIT: val_mini

RL:
  SUCCESS_REWARD: 2.5
  SLACK_REWARD: -1e-3

  POLICY:
    name: "PointNavResNetPolicy"
    OBS_TRANSFORMS:
        ENABLED_TRANSFORMS: ("ResizeShortestEdge", "CenterCropper")

  PPO:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 4
    num_mini_batch: 2
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.2
    num_steps: 64
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 50
    use_normalized_advantage: False

    hidden_size: 512

  DDPPO:
    sync_frac: 0.6
    # The PyTorch distributed backend to use
    distrib_backend: GLOO
    # Visual encoder backbone
    pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
    # Initialize with pretrained weights
    pretrained: False
    # Initialize just the visual encoder backbone with pretrained weights
    pretrained_encoder: False
    # Whether or not the visual encoder backbone will be trained.
    train_encoder: True
    # Whether or not to reset the critic linear layer
    reset_critic: True

    # Model parameters
    backbone: resnet50
    rnn_type: LSTM
    num_recurrent_layers: 2
